# fly.toml app configuration file generated for 10-2-calendario-app-backend on 2023-11-29T21:01:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "10-2-calendario-app-backend"
primary_region = "eze"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
